services:
    dotfiles:
        build:
            context: .
            args:
                USERNAME: ${USER}
        volumes:
          - ./:/home/${USER}/.local/share/chezmoi:ro
        tty: true

